line-length = 120
target-version = "py311"

include = [
    "backend/app/**/*.py",
    "resources/**/*.py",
]

[format]
quote-style = "double"

[lint]
select = ["E", "F", "I", "W", "UP", "ASYNC", "B", "RUF", "FAST"]
ignore = ["E501"]
fixable = ["ALL"]
